version: "3"
services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
    links:
      - redis:redis
      - mongoDB:mongoDB
    volumes:
      - D:\TARGET\Node.js\test-projects\khodam\src\Public\image:/app/src/Public/image
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  mongoDB:
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
  redis_data:
